### ISSUE TITLE
my todo for golden time project

### ISSUE THREAD

**Issue by hjoon0510** [hjoon0510/golden-time#2]
## 해야할 작업 목록: 
- [ ]  opencv-face-recognition-hog 폴더의 소스 이해하기 
- [ ]  opencv-face-recognition-ssd 폴더의 소스 이해하기 
- [ ]  launcher.c 파일에 camera 기능 추가하기 
     - 아이디어1: launcher-hog.c   and launcher-ssd.c   ---> launcher-hog / launcher-ssd
     - 아이디어2: launcher.c    --->  launcher  hog   (or launcher ssd)
- [ ] README.md 파일에 문서 내용 업데이트하기 
- [ ] 작품 지원서에 추가할 데모 사진 작업 하기 ( 라면 박스로 데모 환경 제작하기)
- [ ] 추가 아이디어 생각하기 ( 예: 얼굴을 들이댔을때, 나이가 출력되게 하기, 
     - https://github.com/smahesh29/Gender-and-Age-Detection
